### ISSUE TITLE
get_args gives incorrect with Python 3.6 in case of nested generics

### ISSUE THREAD

**Issue by wyfo** [PrettyWood/typingx#1]
The following example illustrates the issue:
```python
from typing import Collection, List, TypeVar
import typingx

T = TypeVar("T")

print(typingx.get_args(List[Collection[T]][int]))  # should be (typing.Collection[int],)
#> (typing.Collection[~T],)
```

**Comment by PrettyWood** [comment]
Hi @wyfo and thanks a lot for reporting!
Generics on python 3.6 are not supported at all by default so there may still be some hidden bugs. But your usecase should be solved 👍 Will do a `v0.5.2`
